name: E2E tests

on:
  pull_request:
    paths-ignore:
      - 'projects/*testing/**'
      - 'projects/icons/**'
    branches-ignore:
      - 'release**'
  push:
    branches:
      - '!main'
      - '!release**'
      - '!gh-pages**'
      - '!screenshot-bot-storage**'

env:
  CACHE_DIST_KEY: dist-${{ github.head_ref }}-${{ github.ref }}-${{ github.sha }}
  NX_BRANCH: ${{ github.event.number }}
  PATH_NEXT_DIST: dist/gh-pages
  PATH_LOCAL_DIST: dist/demo
  NG_SERVER_PORT: 3333
  ACTIONS_STEP_DEBUG: true

jobs:
  build-demo:
    if: ${{ !contains(github.head_ref, 'release/') }}
    name: Build demo # for reuse in e2e jobs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10

      - name: Try rebase locally for check affected e2e
        uses: ./.github/actions/rebase

      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Mark demo-app directory for persist in cache
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Build branch demo-app
        run: npm run build:demo

  cypress:
    if: ${{ !contains(github.head_ref, 'release/') }}
    needs: [build-demo]
    runs-on: ubuntu-latest
    services:
      sorry-cypress-director:
        image: agoldis/sorry-cypress-director:2.1
        ports:
          - 1234:1234
    strategy:
      fail-fast: false
      matrix:
        specFolder:
          [
            addon-doc,
            addon-charts,
            addon-commerce,
            addon-editor,
            addon-icons,
            addon-mobile,
            addon-preview,
            addon-table,
            addon-tablebars,
            core,
            deep,
            demo,
            kit,
          ]
    name: ${{ matrix.specFolder }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js and Cache
        uses: ./.github/actions/nodejs

      - name: Setup Cypress and Sorry Cypress
        uses: ./.github/actions/cypress
        with:
          cypress-api-url: http://localhost:1234/
          snapshot-path: ./projects/demo-integrations/cypress/snapshots

      - name: Download demo-app from cache
        uses: actions/cache@v3
        with:
          path: dist/demo
          key: ${{ env.CACHE_DIST_KEY }}

      - name: Serve ${{ env.PATH_LOCAL_DIST }}/browser in background
        run: |
          npx nx serve:compiled -- --path ${{ env.PATH_LOCAL_DIST }}/browser \
            & npx wait-on http://localhost:${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.PATH_LOCAL_DIST }}/browser
        run: |
          npm run concurrently \
              "npm run cy2:run:localhost -- --spec '**/${{ matrix.specFolder }}/**/*.spec.ts'" \
              "sleep 20 && npm run cy2:run:localhost -- --spec '**/${{ matrix.specFolder }}/**/*.spec.ts'"

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Copy gh-pages resources to serve `taiga-ui.dev/next` locally
        run: |
          git clone --depth 1 --branch gh-pages https://github.com/Tinkoff/taiga-ui.git ${{ env.PATH_NEXT_DIST }}

      - name: Find and replace baseHref for next snapshot
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: '<base href="/next/">'
          replace: '<base href="/">'
          include: '${{ env.PATH_NEXT_DIST }}/next/index.html'
          regex: false

      - run: cat ${{ env.PATH_NEXT_DIST }}/next/index.html

      - name: Serve ${{ env.PATH_NEXT_DIST }}/next in background
        run: |
          npx nx serve:compiled -- --path ${{ env.PATH_NEXT_DIST }}/next \
            & npx wait-on http://localhost:${{ env.NG_SERVER_PORT }}

      - name: Run screenshot tests on ${{ env.PATH_NEXT_DIST }}/next
        continue-on-error: true
        env:
          # note: need to collect all
          # diff files for lumberjack bot
          CYPRESS_failOnSnapshotDiff: 0
        run: |
          npm run concurrently \
              "npm run cy2:run:demo:next -- --spec '**/${{ matrix.specFolder }}/**/*.spec.ts'" \
              "sleep 20 && npm run cy2:run:demo:next -- --spec '**/${{ matrix.specFolder }}/**/*.spec.ts'"

      - name: Clean up resources
        run: npx kill-port --port ${{ env.NG_SERVER_PORT }}

      - name: Check if diff-output exists
        id: diff-checker
        run: |
          echo "::set-output name=diff_exist::$(find ${{ env.SNAPSHOTS_PATH }} -regex '.*\.diff\.png$' | wc -l | sed -e 's/^[[:space:]]*//')"

      - name: Fall with an error if diff-output exists
        if: ${{ steps.diff-checker.outputs.diff_exist != '0' }}
        run: |
          find ${{ env.SNAPSHOTS_PATH }} -regex '.*\.diff\.png$' -exec echo "{}" \;
          exit 1

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: screenshots-${{ matrix.specFolder }}
          path: ${{ env.SNAPSHOTS_PATH }}
          if-no-files-found: ignore
          retention-days: 5

concurrency:
  group: demo-integrations-${{ github.head_ref }}
  cancel-in-progress: true
